name: Wf Script

on:
  workflow_call:
    inputs:
      operatingSystem:
        description: 'Operating System'
        default: 'ubuntu-latest'
        required: true
        type: string
      npmVersion:
        description: 'npm version'
        required: true
        type: string

jobs: 
    action:
      runs-on: ${{ inputs.operatingSystem }}
      steps:
        - uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20' # Set this to the node version you are using
          
        - run: npm install -g npm@${{ inputs.npmVersion }}
        - run: npm -v
        - run: npm run --workspace=alpha build